
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore the packages
  working-directory: FoodyApiTests
  run: dotnet restore

- name: Build the solution
  working-directory: FoodyApiTests
  run: dotnet build --no-restore

- name: Run all tests
  working-directory: FoodyApiTests
  run: dotnet test --no-build --verbosity normal

